{"name": "500 Internal Server Error при создании заказа без авторизации с валидными ингредиентами.", "status": "skipped", "statusDetails": {"message": "XFAIL Поведение системы при создании заказа неавторизованным пользователем не описано. ОР рекомендован наставником. Подтвержденный баг.\n\nAssertionError: Ожидалось: 500 Bad request, получено {\"success\":true,\"name\":\"Традиционный-галактический флюоресцентный минеральный бургер\",\"order\":{\"number\":5115}}\nassert 200 == 500\n +  where 200 = <Response [200]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x00000256BED72D50>\n\n    @allure.title('500 Internal Server Error при создании заказа без авторизации с валидными ингредиентами.')\n    @allure.description('Создаем payload для заказа.'\n                        ' Отправлям POST запрос на ручку /api/orders без accessToken.'\n                        ' Проверяем, что ответ 500 Internal Server Error.'\n                        ' Комментарий:поведение системы при создании заказа неавторизованным пользователем не описано. ОР рекомендован наставником. Подтвержденный баг.')\n    @pytest.mark.xfail(reason=\"Поведение системы при создании заказа неавторизованным пользователем не описано. ОР рекомендован наставником. Подтвержденный баг.\")\n    def test_create_order_user_not_authorized_valid_ingredients_shows_error_500(self):\n        payload = Order.make_burger()\n        response = Request.post(endpoints.ORDER, payload, '')\n>       assert response.status_code == 500, f'Ожидалось: 500 Bad request, получено {response.text}'\nE       AssertionError: Ожидалось: 500 Bad request, получено {\"success\":true,\"name\":\"Традиционный-галактический флюоресцентный минеральный бургер\",\"order\":{\"number\":5115}}\nE       assert 200 == 500\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_create_order.py:38: AssertionError"}, "description": "Создаем payload для заказа. Отправлям POST запрос на ручку /api/orders без accessToken. Проверяем, что ответ 500 Internal Server Error. Комментарий:поведение системы при создании заказа неавторизованным пользователем не описано. ОР рекомендован наставником. Подтвержденный баг.", "steps": [{"name": "Создание бургера.", "status": "passed", "steps": [{"name": "Создание списка ингредиентов с сортировкой по типу.", "status": "passed", "steps": [{"name": "Получение данных об ингредиентах.", "status": "passed", "steps": [{"name": "GET request.", "status": "passed", "steps": [{"name": "Создание header c токеном авторизации.", "status": "passed", "parameters": [{"name": "token", "value": "''"}], "start": 1741961847791, "stop": 1741961847791}], "parameters": [{"name": "path", "value": "'/api/ingredients'"}, {"name": "access_token", "value": "''"}], "start": 1741961847791, "stop": 1741961847954}], "attachments": [{"name": "Список ингредиентов получен", "source": "b311f9a2-4e90-42e8-947e-21627cca9791-attachment.txt", "type": "text/plain"}], "start": 1741961847791, "stop": 1741961847958}], "start": 1741961847791, "stop": 1741961847958}], "start": 1741961847791, "stop": 1741961847958}, {"name": "POST request.", "status": "passed", "steps": [{"name": "Создание header c токеном авторизации.", "status": "passed", "parameters": [{"name": "token", "value": "''"}], "start": 1741961847958, "stop": 1741961847958}], "parameters": [{"name": "path", "value": "'/api/orders'"}, {"name": "payload", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6d', '61c0c5a71d1f82001bdaaa6d', '61c0c5a71d1f82001bdaaa74', '61c0c5a71d1f82001bdaaa76']}"}, {"name": "access_token", "value": "''"}], "start": 1741961847958, "stop": 1741961848124}], "start": 1741961847790, "stop": 1741961848125, "uuid": "845e6019-0c14-446c-9799-c62c5f96524c", "historyId": "08556a8cc3df2319a1b7848f76d8f6bc", "testCaseId": "08556a8cc3df2319a1b7848f76d8f6bc", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_user_not_authorized_valid_ingredients_shows_error_500", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Поведение системы при создании заказа неавторизованным пользователем не описано. ОР рекомендован наставником. Подтвержденный баг.')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "40252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}